import type { LobbyRankingData } from "./types";

export const MOCK_RANKING_DATA: LobbyRankingData = {
    lobbyId: "epita-apping01",
    lobbyName: "EPITA APPING01",
    currentSeasonId: "season-3",
    seasons: [
        // ============================================
        // SAISON 3 - EN COURS
        // ============================================
        {
            id: "season-3",
            number: 3,
            name: "Piscine SQL",
            status: "current",
            startDate: "2025-11-20T00:00:00Z",
            courses: [
                {
                    id: "s3-course-1",
                    name: "Module 1 - Introduction SQL",
                    date: "2025-11-24",
                    status: "completed",
                    winnerId: "1",
                    winnerName: "Alice",
                    rankings: [
                        { id: "1", username: "Alice", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "3", username: "Benjamin", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                        { id: "6", username: "Emma", points: 10, position: 6, racesWon: 0, racesParticipated: 1, averagePosition: 6, isCurrentUser: false },
                        { id: "7", username: "Lucas", points: 8, position: 7, racesWon: 0, racesParticipated: 1, averagePosition: 7, isCurrentUser: false },
                        { id: "8", username: "Marie", points: 5, position: 8, racesWon: 0, racesParticipated: 1, averagePosition: 8, isCurrentUser: false },
                    ],
                },
                {
                    id: "s3-course-2",
                    name: "Module 2 - SELECT & WHERE",
                    date: "2025-11-25",
                    status: "completed",
                    winnerId: "1",
                    winnerName: "Alice",
                    rankings: [
                        { id: "1", username: "Alice", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "3", username: "Benjamin", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                        { id: "6", username: "Emma", points: 10, position: 6, racesWon: 0, racesParticipated: 1, averagePosition: 6, isCurrentUser: false },
                        { id: "7", username: "Lucas", points: 8, position: 7, racesWon: 0, racesParticipated: 1, averagePosition: 7, isCurrentUser: false },
                        { id: "8", username: "Marie", points: 5, position: 8, racesWon: 0, racesParticipated: 1, averagePosition: 8, isCurrentUser: false },
                    ],
                },
                {
                    id: "s3-course-3",
                    name: "Module 3 - JOIN",
                    date: "2025-11-26",
                    status: "completed",
                    winnerId: "2",
                    winnerName: "Antoine",
                    rankings: [
                        { id: "2", username: "Antoine", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: true },
                        { id: "1", username: "Alice", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "3", username: "Benjamin", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                        { id: "6", username: "Emma", points: 10, position: 6, racesWon: 0, racesParticipated: 1, averagePosition: 6, isCurrentUser: false },
                        { id: "7", username: "Lucas", points: 8, position: 7, racesWon: 0, racesParticipated: 1, averagePosition: 7, isCurrentUser: false },
                        { id: "8", username: "Marie", points: 5, position: 8, racesWon: 0, racesParticipated: 1, averagePosition: 8, isCurrentUser: false },
                    ],
                },
                {
                    id: "s3-course-4",
                    name: "Module 4 - Agrégation",
                    date: "2025-11-27",
                    status: "active",
                    rankings: [
                        { id: "1", username: "Alice", points: 0, position: 1, racesWon: 0, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 0, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "3", username: "Benjamin", points: 0, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 0, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 0, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                        { id: "6", username: "Emma", points: 0, position: 6, racesWon: 0, racesParticipated: 1, averagePosition: 6, isCurrentUser: false },
                        { id: "7", username: "Lucas", points: 0, position: 7, racesWon: 0, racesParticipated: 1, averagePosition: 7, isCurrentUser: false },
                        { id: "8", username: "Marie", points: 0, position: 8, racesWon: 0, racesParticipated: 1, averagePosition: 8, isCurrentUser: false },
                    ],
                },
            ],
            standings: [
                { id: "1", username: "Alice", points: 127, position: 1, racesWon: 2, racesParticipated: 4, averagePosition: 1.5, isCurrentUser: false },
                { id: "2", username: "Antoine", points: 98, position: 2, racesWon: 1, racesParticipated: 4, averagePosition: 1.75, isCurrentUser: true },
                { id: "3", username: "Benjamin", points: 85, position: 3, racesWon: 0, racesParticipated: 4, averagePosition: 3, isCurrentUser: false },
                { id: "4", username: "Clara", points: 72, position: 4, racesWon: 0, racesParticipated: 4, averagePosition: 4, isCurrentUser: false },
                { id: "5", username: "David", points: 65, position: 5, racesWon: 0, racesParticipated: 4, averagePosition: 5, isCurrentUser: false },
                { id: "6", username: "Emma", points: 58, position: 6, racesWon: 0, racesParticipated: 4, averagePosition: 6, isCurrentUser: false },
                { id: "7", username: "Lucas", points: 45, position: 7, racesWon: 0, racesParticipated: 4, averagePosition: 7, isCurrentUser: false },
                { id: "8", username: "Marie", points: 32, position: 8, racesWon: 0, racesParticipated: 4, averagePosition: 8, isCurrentUser: false },
            ],
        },
        // ============================================
        // SAISON 2 - TERMINÉE
        // ============================================
        {
            id: "season-2",
            number: 2,
            name: "Algorithmes",
            status: "completed",
            startDate: "2025-10-01T00:00:00Z",
            endDate: "2025-11-15T00:00:00Z",
            champion: { id: "3", username: "Benjamin", points: 245 },
            courses: [
                {
                    id: "s2-course-1",
                    name: "Tri et recherche",
                    date: "2025-10-05",
                    status: "completed",
                    winnerId: "3",
                    winnerName: "Benjamin",
                    rankings: [
                        { id: "3", username: "Benjamin", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "1", username: "Alice", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                    ],
                },
                {
                    id: "s2-course-2",
                    name: "Récursivité",
                    date: "2025-10-12",
                    status: "completed",
                    winnerId: "2",
                    winnerName: "Antoine",
                    rankings: [
                        { id: "2", username: "Antoine", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: true },
                        { id: "3", username: "Benjamin", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "1", username: "Alice", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                    ],
                },
                {
                    id: "s2-course-3",
                    name: "Structures de données",
                    date: "2025-10-19",
                    status: "completed",
                    winnerId: "3",
                    winnerName: "Benjamin",
                    rankings: [
                        { id: "3", username: "Benjamin", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "1", username: "Alice", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: true },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                    ],
                },
                {
                    id: "s2-course-4",
                    name: "Graphes",
                    date: "2025-10-26",
                    status: "completed",
                    winnerId: "3",
                    winnerName: "Benjamin",
                    rankings: [
                        { id: "3", username: "Benjamin", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "1", username: "Alice", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                    ],
                },
                {
                    id: "s2-course-5",
                    name: "Projet Final",
                    date: "2025-11-10",
                    status: "completed",
                    winnerId: "1",
                    winnerName: "Alice",
                    rankings: [
                        { id: "1", username: "Alice", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "3", username: "Benjamin", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: true },
                        { id: "4", username: "Clara", points: 15, position: 4, racesWon: 0, racesParticipated: 1, averagePosition: 4, isCurrentUser: false },
                        { id: "5", username: "David", points: 12, position: 5, racesWon: 0, racesParticipated: 1, averagePosition: 5, isCurrentUser: false },
                    ],
                },
            ],
            standings: [
                { id: "3", username: "Benjamin", points: 245, position: 1, racesWon: 3, racesParticipated: 5, averagePosition: 1.4, isCurrentUser: false },
                { id: "2", username: "Antoine", points: 198, position: 2, racesWon: 1, racesParticipated: 5, averagePosition: 2.2, isCurrentUser: true },
                { id: "1", username: "Alice", points: 185, position: 3, racesWon: 1, racesParticipated: 5, averagePosition: 2.4, isCurrentUser: false },
                { id: "4", username: "Clara", points: 120, position: 4, racesWon: 0, racesParticipated: 5, averagePosition: 4, isCurrentUser: false },
                { id: "5", username: "David", points: 95, position: 5, racesWon: 0, racesParticipated: 5, averagePosition: 5, isCurrentUser: false },
            ],
        },
        // ============================================
        // SAISON 1 - TERMINÉE
        // ============================================
        {
            id: "season-1",
            number: 1,
            name: "Introduction C",
            status: "completed",
            startDate: "2025-09-01T00:00:00Z",
            endDate: "2025-09-30T00:00:00Z",
            champion: { id: "1", username: "Alice", points: 180 },
            courses: [
                {
                    id: "s1-course-1",
                    name: "Variables et types",
                    date: "2025-09-05",
                    status: "completed",
                    winnerId: "1",
                    winnerName: "Alice",
                    rankings: [
                        { id: "1", username: "Alice", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: true },
                        { id: "3", username: "Benjamin", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                    ],
                },
                {
                    id: "s1-course-2",
                    name: "Pointeurs",
                    date: "2025-09-12",
                    status: "completed",
                    winnerId: "1",
                    winnerName: "Alice",
                    rankings: [
                        { id: "1", username: "Alice", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: false },
                        { id: "3", username: "Benjamin", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "2", username: "Antoine", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: true },
                    ],
                },
                {
                    id: "s1-course-3",
                    name: "Malloc et mémoire",
                    date: "2025-09-19",
                    status: "completed",
                    winnerId: "2",
                    winnerName: "Antoine",
                    rankings: [
                        { id: "2", username: "Antoine", points: 25, position: 1, racesWon: 1, racesParticipated: 1, averagePosition: 1, isCurrentUser: true },
                        { id: "1", username: "Alice", points: 20, position: 2, racesWon: 0, racesParticipated: 1, averagePosition: 2, isCurrentUser: false },
                        { id: "3", username: "Benjamin", points: 18, position: 3, racesWon: 0, racesParticipated: 1, averagePosition: 3, isCurrentUser: false },
                    ],
                },
            ],
            standings: [
                { id: "1", username: "Alice", points: 180, position: 1, racesWon: 2, racesParticipated: 3, averagePosition: 1.33, isCurrentUser: false },
                { id: "2", username: "Antoine", points: 155, position: 2, racesWon: 1, racesParticipated: 3, averagePosition: 2, isCurrentUser: true },
                { id: "3", username: "Benjamin", points: 140, position: 3, racesWon: 0, racesParticipated: 3, averagePosition: 2.67, isCurrentUser: false },
            ],
        },
    ],
};