import type { RaceData } from "./types";

export const MOCK_RACES: Record<string, RaceData> = {
    "course-1": {
        id: "course-1",
        courseName: "Module 1 - Introduction SQL",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 100,
        endsAt: "2025-11-25T18:00:00Z",
        status: "completed",
        participants: [
            { id: "1", username: "Alice", progress: 100, position: 1, isCurrentUser: false },
            { id: "2", username: "Antoine", progress: 100, position: 2, isCurrentUser: true },
            { id: "3", username: "Benjamin", progress: 98, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 95, position: 4, isCurrentUser: false },
            { id: "5", username: "David", progress: 92, position: 5, isCurrentUser: false },
            { id: "6", username: "Emma", progress: 88, position: 6, isCurrentUser: false },
            { id: "7", username: "Lucas", progress: 85, position: 7, isCurrentUser: false },
            { id: "8", username: "Marie", progress: 80, position: 8, isCurrentUser: false },
        ],
        tasks: [
            { id: "t1", title: "Installer PostgreSQL", isCompleted: true },
            { id: "t2", title: "Créer une base de données", isCompleted: true },
            { id: "t3", title: "Comprendre les types de données", isCompleted: true },
            { id: "t4", title: "Quiz final", isCompleted: true },
        ],
    },
    "course-2": {
        id: "course-2",
        courseName: "Module 2 - SELECT & WHERE",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 100,
        endsAt: "2025-11-26T18:00:00Z",
        status: "completed",
        participants: [
            { id: "1", username: "Alice", progress: 100, position: 1, isCurrentUser: false },
            { id: "2", username: "Antoine", progress: 100, position: 2, isCurrentUser: true },
            { id: "3", username: "Benjamin", progress: 95, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 90, position: 4, isCurrentUser: false },
            { id: "5", username: "David", progress: 88, position: 5, isCurrentUser: false },
            { id: "6", username: "Emma", progress: 82, position: 6, isCurrentUser: false },
            { id: "7", username: "Lucas", progress: 78, position: 7, isCurrentUser: false },
            { id: "8", username: "Marie", progress: 72, position: 8, isCurrentUser: false },
        ],
        tasks: [
            { id: "t1", title: "SELECT basique", isCompleted: true },
            { id: "t2", title: "Clause WHERE", isCompleted: true },
            { id: "t3", title: "Opérateurs de comparaison", isCompleted: true },
            { id: "t4", title: "LIKE et wildcards", isCompleted: true },
            { id: "t5", title: "Exercices pratiques", isCompleted: true },
        ],
    },
    "course-3": {
        id: "course-3",
        courseName: "Module 3 - JOIN",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 100,
        endsAt: "2025-11-27T18:00:00Z",
        status: "completed",
        participants: [
            { id: "2", username: "Antoine", progress: 100, position: 1, isCurrentUser: true },
            { id: "1", username: "Alice", progress: 98, position: 2, isCurrentUser: false },
            { id: "3", username: "Benjamin", progress: 92, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 88, position: 4, isCurrentUser: false },
            { id: "5", username: "David", progress: 85, position: 5, isCurrentUser: false },
            { id: "6", username: "Emma", progress: 80, position: 6, isCurrentUser: false },
            { id: "7", username: "Lucas", progress: 75, position: 7, isCurrentUser: false },
            { id: "8", username: "Marie", progress: 70, position: 8, isCurrentUser: false },
        ],
        tasks: [
            { id: "t1", title: "INNER JOIN", isCompleted: true },
            { id: "t2", title: "LEFT JOIN", isCompleted: true },
            { id: "t3", title: "RIGHT JOIN", isCompleted: true },
            { id: "t4", title: "FULL OUTER JOIN", isCompleted: true },
            { id: "t5", title: "Jointures multiples", isCompleted: true },
        ],
    },
    "course-4": {
        id: "course-4",
        courseName: "Module 4 - Agrégation",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: true,
        myProgress: 65,
        endsAt: "2025-11-28T18:00:00Z",
        status: "active",
        participants: [
            { id: "1", username: "Alice", progress: 78, position: 1, isCurrentUser: false },
            { id: "2", username: "Antoine", progress: 65, position: 2, isCurrentUser: true },
            { id: "3", username: "Benjamin", progress: 52, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 45, position: 4, isCurrentUser: false },
            { id: "5", username: "David", progress: 38, position: 5, isCurrentUser: false },
            { id: "6", username: "Emma", progress: 32, position: 6, isCurrentUser: false },
            { id: "7", username: "Lucas", progress: 25, position: 7, isCurrentUser: false },
            { id: "8", username: "Marie", progress: 18, position: 8, isCurrentUser: false },
        ],
        tasks: [
            {
                id: "t1",
                title: "Module Auth",
                isCompleted: false,
                subtasks: [
                    { id: "s1", title: "COUNT et SUM", isCompleted: true },
                    { id: "s2", title: "AVG et MIN/MAX", isCompleted: true },
                    { id: "s3", title: "Fonctions avancées", isCompleted: false },
                    { id: "s4", title: "Quiz intermédiaire", isCompleted: false },
                ],
            },
            {
                id: "t2",
                title: "Module Salons",
                isCompleted: false,
                subtasks: [
                    { id: "s5", title: "GROUP BY basique", isCompleted: true },
                    { id: "s6", title: "GROUP BY multiple", isCompleted: false },
                    { id: "s7", title: "Exercices", isCompleted: false },
                ],
            },
            { id: "t3", title: "Tests unitaires", isCompleted: true },
            { id: "t4", title: "Documentation API", isCompleted: false },
            { id: "t5", title: "Intégration CI/CD", isCompleted: true },
        ],
    },
    "course-5": {
        id: "course-5",
        courseName: "Module 5 - Sous-requêtes",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 0,
        endsAt: "2025-11-29T18:00:00Z",
        status: "scheduled",
        participants: [
            { id: "1", username: "Alice", progress: 0, position: 1, isCurrentUser: false },
            { id: "2", username: "Antoine", progress: 0, position: 2, isCurrentUser: true },
            { id: "3", username: "Benjamin", progress: 0, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 0, position: 4, isCurrentUser: false },
            { id: "5", username: "David", progress: 0, position: 5, isCurrentUser: false },
            { id: "6", username: "Emma", progress: 0, position: 6, isCurrentUser: false },
            { id: "7", username: "Lucas", progress: 0, position: 7, isCurrentUser: false },
            { id: "8", username: "Marie", progress: 0, position: 8, isCurrentUser: false },
        ],
        tasks: [
            { id: "t1", title: "Sous-requêtes scalaires", isCompleted: false },
            { id: "t2", title: "Sous-requêtes dans WHERE", isCompleted: false },
            { id: "t3", title: "Sous-requêtes corrélées", isCompleted: false },
            { id: "t4", title: "EXISTS et NOT EXISTS", isCompleted: false },
            { id: "t5", title: "Projet pratique", isCompleted: false },
        ],
    },
    "course-6": {
        id: "course-6",
        courseName: "Module 6 - Transactions",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 0,
        endsAt: "2025-11-30T18:00:00Z",
        status: "scheduled",
        participants: [
            { id: "1", username: "Alice", progress: 0, position: 1, isCurrentUser: false },
            { id: "2", username: "Antoine", progress: 0, position: 2, isCurrentUser: true },
            { id: "3", username: "Benjamin", progress: 0, position: 3, isCurrentUser: false },
            { id: "4", username: "Clara", progress: 0, position: 4, isCurrentUser: false },
        ],
        tasks: [
            { id: "t1", title: "Propriétés ACID", isCompleted: false },
            { id: "t2", title: "BEGIN et COMMIT", isCompleted: false },
            { id: "t3", title: "ROLLBACK", isCompleted: false },
            { id: "t4", title: "Savepoints", isCompleted: false },
            { id: "t5", title: "Isolation levels", isCompleted: false },
        ],
    },
    "course-7": {
        id: "course-7",
        courseName: "Module 7 - Projet Final",
        salonName: "EPITA APPING01",
        salonId: "epita-apping01",
        isLive: false,
        myProgress: 0,
        endsAt: "2025-12-01T18:00:00Z",
        status: "draft",
        participants: [],
        tasks: [
            { id: "t1", title: "Conception du schéma", isCompleted: false },
            { id: "t2", title: "Création des tables", isCompleted: false },
            { id: "t3", title: "Requêtes complexes", isCompleted: false },
            { id: "t4", title: "Optimisation", isCompleted: false },
            { id: "t5", title: "Présentation", isCompleted: false },
        ],
    },
};

// Helper pour récupérer une course par ID
export function getRaceById(id: string): RaceData | null {
    return MOCK_RACES[id] || null;
}

// Export pour compatibilité avec l'ancien code
export const MOCK_RACE = MOCK_RACES["course-4"];